### ISSUE TITLE
Failed to Execute

### ISSUE THREAD

**Issue by feylen** [RT-Thread/mpy-snippets#58]
PS /Users/sean/.vscode/extensions/rt-thread.rt-thread-micropython-1.0.7/ampy> ./cli_mac -p /dev/cu.usbmodem3164395C32382 repl
Traceback (most recent call last):
  File "cli.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/summer/Desktop/work/python3_venv_cli/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/serial/tools/list_ports.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/summer/Desktop/work/python3_venv_cli/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/summer/Desktop/work/python3_venv_cli/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
[47449] Failed to execute script cli

PS /Users/sean> sw_vers                
ProductName:    macOS
ProductVersion: 11.2.1
BuildVersion:   20D74

**Comment by SummerGift** [comment]
I think this error is caused by Mac OS's upgrade, the MicroPython tool doesn't support MacOS's current version very well.

**Comment by feylen** [comment]
Thank you for your reply. I will await an update and try it again.Cheers,Seanvia Newton MailOn Sat, Feb 27, 2021 at 9:26 PM, 我夏了夏天 <notifications@github.com> wrote:
I think this error is caused by Mac OS's upgrade, the MicroPython tool doesn't support MacOS's current version very well.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RT-Thread/mpy-snippets/issues/58#issuecomment-787260030",
"url": "https://github.com/RT-Thread/mpy-snippets/issues/58#issuecomment-787260030",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by winnie2012** [comment]
I have the same problem 

MacOS Big Sur 11.6

**Comment by Sloaix** [comment]
Same problem on macOS Monterey 12.2.1.
